Repository Libera-Chat/libera-chat.github.io, pull requests merged in 2021-06, with the labels that each got.

#73 jekyll backend liquid query for channel modes excludes restricted
  content/_guides/channelmodes.md
Labels: Area: Jekyll, Type: Bug

#79 List our organisation number
  about.md
  bylaws.md
  privacy.md
Labels: Area: Governance, Type: New

#76 GitHub action on PR: markdownlint
  .github/workflows/lint.yml
  .gitignore
  .markdownlint.yml
  .markdownlintignore
  _includes/modetable.md
  chanreg.md
  content/_guides/certfp.md
  content/_guides/channelmodes.md
  content/_guides/connect.md
  content/_guides/extbans.md
  content/_guides/findingchannels.md
  content/_guides/registration.md
  content/_guides/sasl.md
  content/_guides/sasl/epic5.md
  content/_guides/sasl/irccloud.md
  content/_guides/sasl/irssi.md
  content/_guides/sasl/kvirc.md
  content/_guides/sasl/revolution.md
  content/_guides/sasl/weechat.md
  content/_guides/sendpass.md
  content/_guides/usermodes.md
  content/_posts/2021-05-25-one-week-of-libera-chat.md
  guidelines.md
  guides.md
  package.json
  privacy.md
Labels: Area: Jekyll, Type: New

#81 adding bot documentation
  content/_guides/bots.md
Labels: Area: Guides, Type: New

#94 Uses onion service as technical term for Tor service
  content/_guides/connect.md
Labels: Area: Guides, Type: Enhancement

#92 New contributing docs
  _data/nav.yml
  contributing/development.md
  contributing/sponsor.md
Labels: Area: General, Type: New

#98 Explicitly add webrick into the Gemfile
  Gemfile
  Gemfile.lock
Labels: Area: Jekyll, Type: Bug

#89 Only list TLS details in the menu
  _data/nav.yml
Labels: Area: General, Type: Enhancement

#57 update network name used in the weechat configurations
  content/_guides/certfp.md
Labels: Area: Guides, Type: Enhancement
